README.md

Regarding our test of the instructions setting up the website I've improved the section in the README.

docs(website): improve website section

---

package-lock.json
package.json

fix: added missing storybook package

---

libs/react-components/src/index.ts
libs/react-components/src/lib/UserCard.spec.tsx
libs/react-components/src/lib/UserCard.stories.tsx
libs/react-components/src/lib/UserCard.tsx

feat(react-components): added UserCard with organization info

---

apps/website-backend/.ddev/config.yaml

feat(website-backend): use apache instead of nginx as webserver

---

libs/design-system/src/stories/Fonts.stories.tsx
libs/design-system/src/theme.js
libs/design-system/tailwind.config.js

refactor(design-system): update font sizes in theme

---

apps/website/src/pages/index.spec.tsx

fix(website): initial gatsby test always fails

---

libs/react-components/src/lib/EventFeed/EventFeedItem.tsx
libs/react-components/src/lib/NewsFeed/NewsFeedItem.tsx

refactor(react-components): remove superfluous states

---

libs/react-components/src/lib/OrganizationBox/OrganizationBox.spec.tsx
libs/react-components/src/lib/OrganizationBox/OrganizationBox.tsx
libs/react-components/src/lib/OrganizationBox/OrganizationBoxContainer.tsx
libs/react-components/src/lib/OrganizationBox/index.stories.tsx
libs/react-components/src/lib/OrganizationBox/utils.tsx

feat/#7-small_organization_box 

---

apps/website/static/.htaccess

- BEWARE this is an adapted version of https://raw.githubusercontent.com/h5bp/html5-boilerplate/main/dist/.htaccess with a lot of sane defaults (may lead to problems for us?)
- CHANGED: enabled redirect 80->443
Closes #80

added .htaccess (with redirect 80->443) to static folder

---

apps/website-backend/.gitignore
apps/website-backend/deploy.php

- added pull tasks to deployer: pull:db + pull:uploads from a <stage>
-needs documentation!
Closes #65

feat(website-backend)): Deployer tasks to pull live data (#65)

---

apps/website/src/components/header.tsx

fix(website): menu item not highlighted

---

apps/website-backend/data/acf/acf-export.json
apps/website/gatsby-node.js
apps/website/src/pages/index.tsx
apps/website/src/pages/news.tsx
apps/website/src/templates/News.tsx

feat(*): add news content 

---

apps/website/src/pages/index.tsx
apps/website/src/utils/dataTransformer.spec.ts
apps/website/src/utils/dataTransformer.ts
libs/react-components/src/index.ts
libs/react-components/src/lib/NewsFeed/NewsFeed.tsx
libs/react-components/src/lib/NewsFeed/NewsFeedItem.tsx

feat(*): add news feed component to landing page

---

apps/website/src/pages/index.tsx
apps/website/src/pages/news.tsx
apps/website/src/templates/News.tsx
apps/website/src/utils/dataTransformer.spec.ts
apps/website/src/utils/dataTransformer.ts
libs/design-system/tailwind.config.js
libs/react-components/src/lib/NewsFeed/NewsFeed.spec.tsx
libs/react-components/src/lib/NewsFeed/NewsFeed.tsx
libs/react-components/src/lib/NewsFeed/NewsFeedItem.spec.tsx
libs/react-components/src/lib/NewsFeed/NewsFeedItem.tsx
libs/react-components/src/lib/NewsFeed/index.stories.tsx
libs/react-components/src/lib/NewsFeed/utils.tsx

feat(website): add news feed component to news overview

---

libs/react-components/src/index.ts
libs/react-components/src/lib/NewsFeed/NewsFeedItem.tsx
libs/react-components/src/lib/UserCard/UserCard.tsx
libs/react-components/src/lib/types.d.ts

fix(react-components): ambiguity exporting image interface

---

apps/website-backend/data/acf/acf-export.json
apps/website/src/pages/index.tsx
apps/website/src/pages/news.tsx
apps/website/src/pages/project.tsx
apps/website/src/templates/News.tsx
apps/website/src/utils/dataTransformer.spec.ts
apps/website/src/utils/dataTransformer.ts
libs/react-components/src/index.ts
libs/react-components/src/lib/OrganizationBox/OrganizationBox.tsx
libs/react-components/src/lib/OrganizationBox/OrganizationBoxContainer.tsx
libs/react-components/src/lib/OrganizationBox/index.stories.tsx

please merge + be aware to import acf for organisation
Closes #123

feat(*): small organization box and container (#123)

---

libs/react-components/src/index.ts
libs/react-components/src/lib/ContactCard/ContactCard.spec.tsx
libs/react-components/src/lib/ContactCard/ContactCard.stories.tsx
libs/react-components/src/lib/ContactCard/ContactCard.tsx

feat(react-components): build contact component

---

apps/website/src/pages/project.tsx
libs/design-system/tailwind.config.js
libs/react-components/src/lib/UserCard/UserCard.tsx
libs/react-components/src/lib/UserCard/UserCardContainer.tsx

feat(*): add texts to project page

---

apps/website-backend/web/app/plugins/schedule-container/build/index.asset.php
apps/website-backend/web/app/plugins/schedule-container/build/index.js
apps/website-backend/web/app/plugins/schedule-container/src/edit.js
apps/website-backend/web/app/plugins/schedule-container/src/save.js
apps/website-backend/web/app/plugins/schedule-item/block.json
apps/website-backend/web/app/plugins/schedule-item/build/index.asset.php
apps/website-backend/web/app/plugins/schedule-item/build/index.js
apps/website-backend/web/app/plugins/schedule-item/src/edit.js
apps/website-backend/web/app/plugins/schedule-item/src/save.js

feat(website-backend): gutenberg block for time schedule accordion

---

apps/website/src/pages/project.tsx
apps/website/src/utils/dataTransformer.spec.ts
apps/website/src/utils/dataTransformer.ts

feat(website): add team members

---

apps/website/src/pages/index.tsx
apps/website/src/pages/project.tsx
apps/website/src/utils/dataTransformer.spec.ts
apps/website/src/utils/dataTransformer.ts

fix(website): image optimization fails on svgs

---

apps/website/src/pages/mintcommunity.tsx
apps/website/src/pages/mintmachen.tsx
apps/website/src/pages/mintvernetzt.tsx

retrieve specific contact information from graphql
Closes #199

feat(website): added page contact from graphql

---

apps/website/src/utils/dataTransformer.spec.ts
apps/website/src/utils/dataTransformer.ts

feat(website): sorting of child and sibling events

---

apps/website/src/pages/project.tsx

refactor(website): textual changes project

---

apps/website/src/pages/mintmachen.tsx

fix(website): link /mintmachen/ to /mintcommunity/

---

apps/website/src/components/footer.tsx
apps/website/src/components/header.tsx
apps/website/src/pages/about.spec.tsx
apps/website/src/pages/about.tsx
apps/website/src/pages/index.tsx
apps/website/src/pages/pakt/{MarkdownRemark.frontmatter__slug}.tsx
apps/website/src/pages/projects.spec.tsx
apps/website/src/pages/projects.tsx
apps/website/src/utils/dataTransformer.spec.ts
apps/website/src/utils/dataTransformer.ts

refactor(website): rename project and topics

---

apps/website/src/components/header.tsx
apps/website/src/components/layout.tsx

- previous solution looked at client side path
- location.pathname is present in ssr
- removed superflous props in header component

renders teaser in SSR not on client side

---

apps/website/src/pages/events.tsx
apps/website/src/pages/index.tsx
apps/website/src/templates/Event.tsx
apps/website/src/utils/dataTransformer.ts
libs/design-system/src/tailwind.css
libs/react-components/src/lib/ContactCard/ContactCard.spec.tsx
libs/react-components/src/lib/ContactCard/ContactCard.tsx

fix(website): minor issues regarding events pages

---

apps/website/src/pages/index.tsx

fix(website): sort organisations in alphabetical order

---

apps/website/src/pages/events.tsx
apps/website/src/pages/index.tsx
apps/website/src/pages/news.tsx
libs/react-components/src/lib/EventFeed/EventFeedItem.tsx
libs/react-components/src/lib/NewsFeed/NewsFeedItem.tsx

fix(website): HTML entities show up in feed item excerpt

---

apps/website/src/components/affix.tsx
apps/website/src/pages/events.tsx
apps/website/src/pages/news.tsx
libs/react-components/src/lib/Heading/Heading.tsx
libs/react-components/src/lib/NewsFeed/NewsFeed.tsx

fix(website): scroll behavior after filter click

---

apps/website/src/pages/index.tsx

If its to hard to hit the small link text, we can also link the whole header part.
closes #298

refactor(website): added see all links to teaser

---

apps/website/src/pages/pakt/{MarkdownRemark.frontmatter__slug}.tsx

features static addition of target blank in every link in PAKT content
Closes  #310

feat(website): open external links in PAKT pages in new tab

---

apps/website-backend/web/app/plugins/schedule-container/package-lock.json
apps/website/src/components/header.tsx
apps/website/src/components/layout.tsx
apps/website/src/pages/events.tsx
apps/website/src/pages/pakt.tsx
apps/website/src/pages/pakt/{MarkdownRemark.frontmatter__slug}.tsx
libs/design-system/src/stories/Fonts.stories.tsx
libs/design-system/src/tailwind.css
libs/react-components/src/index.ts
libs/react-components/src/lib/Link/Link.spec.tsx
libs/react-components/src/lib/Link/Link.tsx
libs/react-components/src/lib/Link/index.stories.tsx
package.json

Added current state of fonts. There was and is no font weight 700 (bold) included. Maybe we should talk...

refactor(website): removed google font links and added fontsource/source-sans-pro

---

apps/website/src/pages/events.tsx
apps/website/src/pages/index.tsx
apps/website/src/utils/dataTransformer.spec.ts
apps/website/src/utils/dataTransformer.tsx
apps/website/src/utils/eventFilter.spec.ts
apps/website/src/utils/eventFilter.ts
libs/react-components/src/lib/EventTeaser/EventTeaserItem.tsx

feat(website) hide events (#308)
